name: ld34
description: A ld34 game
publish_to: none

environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  dartemis:
    git:
      url: git://github.com/denniskaselow/dartemis.git
  gamedev_helpers:
    git:
      url: git://github.com/kayzgames/gamedev_helpers.git
dev_dependencies:
  build_runner: ^0.9.0
  build_web_compilers: any
  dartemis_builder:
    git: git://github.com/denniskaselow/dartemis_builder.git
