name: ld34
description: A ld34 game
dependencies:
  browser: any
  dartemis:
    git:
      url: git://github.com/denniskaselow/dartemis.git
      ref: feature/ddc
  dartemis_transformer:
    git:
      url: git://github.com/denniskaselow/dartemis_transformer.git
      ref: feature/ddc
  gamedev_helpers:
    git:
      url: git://github.com/kayzgames/gamedev_helpers.git
      ref: feature/ddc
  dart_to_js_script_rewriter: any
transformers:
- dart_to_js_script_rewriter
- dartemis_transformer:
    additionalLibraries:
    - gamedev_helpers/gamedev_helpers.dart
    - gamedev_helpers/gamedev_helpers_shared.dart
- $dart2js:
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives