name: ld34
description: A ld34 game
dependencies:
  dartemis:
    git:
      url: git://github.com/denniskaselow/dartemis.git
      ref: feature/ddc
  gamedev_helpers:
    git:
      url: git://github.com/kayzgames/gamedev_helpers.git
      ref: feature/ddc
dev_dependencies:
  build_runner: ^0.8.0
  build_web_compilers: any
  dartemis_builder:
    git: git://github.com/denniskaselow/dartemis_builder.git
